### ISSUE TITLE
Random fatal crashes

### ISSUE THREAD

**Issue by WickedSchnitzel** [LMD-inc/teleportation-runes#10]
Running on 64 bit Windows with 8 GB RAM
Version: v1.15.7 (Stable)10/30/2021 3:24:53 PM: Critical error occurred
System.ArgumentException: Fatal: Trying to render an uninitialized or disposed mesh
at Vintagestory.Client.NoObf.ClientPlatformWindows.RenderMesh(MeshRef modelRef)
at Vintagestory.GameContent.BEAnimatableRenderer.OnRenderFrame(Single dt, EnumRenderStage stage)
at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
at _gt983m53spH3zIRFvTrVgBj5MUb._m2KVBUzhniiatiiNT9yOoXoOOvL(Single )
at _2hFm1B1DwOk1Z7yF6DtBdLeBFKaA._5soGXezAcR5oyhhq2pmELCuEn2M(Single )
at _2hFm1B1DwOk1Z7yF6DtBdLeBFKaA._ZzmaNk5IGbtvQ61ssCzCszyBw2n(Single )
at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
at OpenTK.GameWindow.DispatchRenderFrame()
at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
at _LiN8p156auXcqjjOW5aVAZ0QkUc._fwMbTl3XHB2eqbxoLfc3FpMIE00(_CFodeVozKjT5VhVV66Wv4Bd7r3c , String[] )
at _qBF2AKwdIhCkNZsjxBA24g20vlH._fwMbTl3XHB2eqbxoLfc3FpMIE00(ThreadStart )

**Comment by snakeriot** [comment]
Hi @gentleZen 

Thank you for the report! Unfortunately I've faced this issue and it's related to in-game code.

As far as I can see - it caused by attempt to render particles on teleport, but I've not found a way to fix it from my code (since as you can see in the stack trace there are no mod-related classes, it's all in-game entities)

I've tried to bring developer's attention in game developers discord channel, and hope that it will be fixed in next game releases.

And sorry for late response, because of the number of in-game issues I've temporarily stopped playing and making mods for VintageStory. But I really hope that this game will get better with time.
